import { Injectable, Logger } from '@nestjs/common';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ActivitySlot {
  name: string;
  time: string;          // "HH:MM AM/PM"
  duration: string;      // "2 hours", "90 minutes", "1.5 hours"
  estimatedCost: number;
  description?: string;
  _replanned?: boolean;
  [key: string]: any;
}

export interface ItineraryDay {
  day: number;
  date?: string;
  activities: ActivitySlot[];
  totalCost?: number;
}

export interface ImpactChange {
  /** Type of trigger for this change */
  trigger: 'time_shift' | 'cost_change' | 'activity_swap' | 'drop' | 'add';
  dayIndex: number;
  activityIndex: number;
  originalActivity: ActivitySlot;
  updatedActivity: Partial<ActivitySlot>;
  reason: string;
}

export interface ImpactResult {
  /** Cascade changes generated by the engine */
  cascadeChanges: ImpactChange[];
  /** Total budget delta across all affected days (negative = savings) */
  budgetDelta: number;
  /** Minutes lost / gained across the day */
  timeDeltaMinutes: number;
  /** Human-readable risk summary */
  riskSummary: string;
  /** Whether any hotel/flight logistics are threatened */
  logisticsRisk: boolean;
  /** Days with cascaded changes */
  affectedDays: number[];
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Parse duration string → minutes */
function parseDurationMinutes(duration: string): number {
  if (!duration) return 60;
  const lower = duration.toLowerCase();
  let total = 0;
  const hourMatch = lower.match(/(\d+(?:\.\d+)?)\s*h/);
  const minMatch = lower.match(/(\d+)\s*m(?:in)?/);
  if (hourMatch) total += Math.round(parseFloat(hourMatch[1]) * 60);
  if (minMatch)  total += parseInt(minMatch[1], 10);
  if (total === 0) {
    // Plain number assumed minutes
    const plain = parseFloat(lower);
    if (!isNaN(plain)) total = plain > 12 ? plain : plain * 60;
  }
  return total || 60;
}

/** Parse "HH:MM AM/PM" or "HH:MM" → minutes since midnight */
function parseTimeMins(time: string): number {
  if (!time) return 0;
  const t = time.trim().toUpperCase();
  const m = t.match(/(\d{1,2}):(\d{2})\s*(AM|PM)?/);
  if (!m) return 0;
  let h = parseInt(m[1], 10);
  const min = parseInt(m[2], 10);
  const ampm = m[3];
  if (ampm === 'PM' && h < 12) h += 12;
  if (ampm === 'AM' && h === 12) h = 0;
  return h * 60 + min;
}

/** Format minutes-since-midnight back to "HH:MM AM/PM" */
function formatTime(mins: number): string {
  const clamped = Math.max(0, Math.min(mins, 23 * 60 + 59));
  const h24 = Math.floor(clamped / 60);
  const m = clamped % 60;
  const ampm = h24 >= 12 ? 'PM' : 'AM';
  const h12 = h24 % 12 || 12;
  return `${h12}:${String(m).padStart(2, '0')} ${ampm}`;
}

// ─── Service ──────────────────────────────────────────────────────────────────

/**
 * ImpactEngineService — Calculates ripple effects when an itinerary activity changes.
 *
 * Key capabilities:
 *   - Time cascade: if activity A shifts/runs long → push B, C, D forward
 *   - Budget cascade: accumulate cost deltas across day and week
 *   - Drop detection: if pushing causes activities to bleed past 10 PM, drop lowest-priority
 *   - Logistics flag: detect if hotel check-in / departure flight is threatened
 */
@Injectable()
export class ImpactEngineService {
  private readonly logger = new Logger(ImpactEngineService.name);

  /**
   * Calculate full cascade impact of a single activity change.
   *
   * @param days         Full itinerary days array (shallow copy — not mutated)
   * @param dayIndex     0-based index of the day being changed
   * @param actIndex     0-based index of the activity within that day
   * @param shiftMins    Positive = pushed later, negative = earlier
   * @param costDelta    Change in cost for this activity (can be 0)
   * @param trigger      Why the change is happening
   */
  calculateImpact(
    days: ItineraryDay[],
    dayIndex: number,
    actIndex: number,
    shiftMins: number,
    costDelta: number,
    trigger: ImpactChange['trigger'],
    reason: string,
  ): ImpactResult {
    const cascadeChanges: ImpactChange[] = [];
    let totalBudgetDelta = costDelta;
    let totalTimeDelta = shiftMins;
    let logisticsRisk = false;
    const affectedDaysSet = new Set<number>();

    const day = days[dayIndex];
    if (!day) {
      return {
        cascadeChanges: [],
        budgetDelta: 0,
        timeDeltaMinutes: 0,
        riskSummary: 'Day not found',
        logisticsRisk: false,
        affectedDays: [],
      };
    }

    // ── Step 1: Cascade time shift through remaining activities in the day ──
    if (shiftMins !== 0) {
      const activities = day.activities;
      let rollingShift = shiftMins;

      for (let ai = actIndex; ai < activities.length; ai++) {
        const act = activities[ai];
        const origTimeMins = parseTimeMins(act.time);
        const newTimeMins = origTimeMins + rollingShift;
        const durationMins = parseDurationMinutes(act.duration);

        // Detect activities running past 10 PM (22:00) — flag logistics risk
        if (newTimeMins + durationMins > 22 * 60) {
          logisticsRisk = true;
          // If this is a hotel check-in or flight, mark HIGH risk
          if (/hotel|check.?in|flight|airport|depart/i.test(act.name || '')) {
            logisticsRisk = true;
          }
        }

        // If activity now runs past midnight (> 23:59), consider dropping it
        if (newTimeMins > 23 * 60 + 30) {
          cascadeChanges.push({
            trigger: 'drop',
            dayIndex,
            activityIndex: ai,
            originalActivity: act,
            updatedActivity: { name: `[DROPPED] ${act.name}` },
            reason: `Pushed past midnight by accumulated ${shiftMins}-minute delay — no time remaining`,
          });
          affectedDaysSet.add(dayIndex);
          totalBudgetDelta -= (act.estimatedCost || 0);
          continue;
        }

        if (newTimeMins !== origTimeMins) {
          cascadeChanges.push({
            trigger: 'time_shift',
            dayIndex,
            activityIndex: ai,
            originalActivity: act,
            updatedActivity: { time: formatTime(newTimeMins) },
            reason: `Shifted ${rollingShift > 0 ? '+' : ''}${rollingShift} min due to ${reason}`,
          });
          affectedDaysSet.add(dayIndex);
        }

        // Absorption: if there's buffer (gap to next activity), reduce rolling shift
        if (ai < activities.length - 1) {
          const nextOrigTimeMins = parseTimeMins(activities[ai + 1].time);
          const endOfThis = origTimeMins + durationMins;
          const buffer = nextOrigTimeMins - endOfThis;
          const absorbed = Math.min(rollingShift, Math.max(0, buffer));
          rollingShift = Math.max(0, rollingShift - absorbed);
        }
      }
    }

    // ── Step 2: Cost cascade ─────────────────────────────────────────────────
    if (costDelta !== 0) {
      affectedDaysSet.add(dayIndex);
      // If total day goes > 20% over budget, flag logistics risk
      const dayTotal = day.activities.reduce((s, a) => s + (a.estimatedCost || 0), 0);
      if (dayTotal > 0 && costDelta / dayTotal > 0.2) {
        logisticsRisk = true;
      }
    }

    // ── Step 3: Cross-day ripple (if shiftMins blows the end of day) ─────────
    if (logisticsRisk && dayIndex + 1 < days.length) {
      const nextDay = days[dayIndex + 1];
      if (nextDay?.activities?.length) {
        const firstNextAct = nextDay.activities[0];
        cascadeChanges.push({
          trigger: 'time_shift',
          dayIndex: dayIndex + 1,
          activityIndex: 0,
          originalActivity: firstNextAct,
          updatedActivity: {
            description: `⚠️ Check Day ${day.day} — delay may affect hotel check-in / morning start`,
          },
          reason: 'Prior day ran late — review morning schedule',
        });
        affectedDaysSet.add(dayIndex + 1);
      }
    }

    // ── Step 4: Risk summary ─────────────────────────────────────────────────
    let riskSummary = '';
    if (cascadeChanges.length === 0 && !logisticsRisk) {
      riskSummary = 'Low impact — change absorbed within buffer time.';
    } else if (cascadeChanges.some(c => c.trigger === 'drop')) {
      const dropped = cascadeChanges.filter(c => c.trigger === 'drop').length;
      riskSummary = `High impact — ${dropped} activity(ies) cannot fit and will be dropped. Review Day ${dayIndex + 1}.`;
    } else if (logisticsRisk) {
      riskSummary = `Medium impact — ${cascadeChanges.length} activity time(s) shifted. Hotel check-in or departure may be at risk.`;
    } else {
      riskSummary = `Low-medium impact — ${cascadeChanges.length} activity time(s) shifted by up to ${Math.abs(shiftMins)} minutes.`;
    }

    this.logger.log(
      `⚙️ Impact: day=${dayIndex}, shift=${shiftMins}min, costΔ=${costDelta}, ` +
      `cascades=${cascadeChanges.length}, logisticsRisk=${logisticsRisk}`,
    );

    return {
      cascadeChanges,
      budgetDelta: totalBudgetDelta,
      timeDeltaMinutes: totalTimeDelta,
      riskSummary,
      logisticsRisk,
      affectedDays: Array.from(affectedDaysSet).sort(),
    };
  }

  /**
   * Simulate replacing an activity entirely and compute impact.
   * Useful when a POI is closed or weather forces a swap.
   */
  simulateSwap(
    days: ItineraryDay[],
    dayIndex: number,
    actIndex: number,
    newActivity: Partial<ActivitySlot>,
    reason: string,
  ): ImpactResult {
    const day = days[dayIndex];
    if (!day) return this.emptyResult();

    const orig = day.activities[actIndex];
    if (!orig) return this.emptyResult();

    const origDur = parseDurationMinutes(orig.duration);
    const newDur = parseDurationMinutes(newActivity.duration || orig.duration);
    const durationDelta = newDur - origDur;
    const costDelta = (newActivity.estimatedCost ?? orig.estimatedCost) - orig.estimatedCost;

    return this.calculateImpact(
      days, dayIndex, actIndex + 1, durationDelta, costDelta, 'activity_swap', reason,
    );
  }

  private emptyResult(): ImpactResult {
    return { cascadeChanges: [], budgetDelta: 0, timeDeltaMinutes: 0, riskSummary: 'No impact', logisticsRisk: false, affectedDays: [] };
  }
}
